"""Generate modules/*/CLAUDE.md from one template (SPEC D05-H).

Edit MODULES / TEMPLATE here and rerun; never hand-edit the generated files.
Run from backend/core: python scripts/gen_module_claude.py
"""

from pathlib import Path

TEMPLATE = """\
<!-- GENERATED by scripts/gen_module_claude.py - edit the generator, not this file -->
# {name} module

{purpose}

**Spec pointer:** {spec}

## Boundary rules
- Never import from other modules (import-linter enforces independence);
  cross-module effects go through the Redis Streams event bus
  (shared/events.py, ADR-0008) or the owning module's public service
  interface.
- Every route lives on a SecureRouter (shared/security.py, ADR-0009);
  `public=True` requires updating backend/core/public_routes.txt in the
  same PR.
- IDs are UUIDv7 (ADR-0003); every list endpoint is cursor-paginated
  (shared/pagination.py, ADR-0004) - OFFSET is banned by a test gate.
- User-generated content defaults to `pending` moderation state.

## Never do
- Never log request bodies or query strings - this module {pii_note}.
  PII scrubbing (shared/telemetry.py) is the last line of defence, not a
  licence.
- Never read another module's tables directly.
- Never bypass rate limiting or add an undeclared public route.
{extra_never}
"""

MODULES: dict[str, dict[str, str]] = {
    "identity": {
        "purpose": "AgriID SSO: users, sessions, OAuth2 code + PKCE, RBAC roles.",
        "spec": "Sprint 1, D06-D14 (docs/Execution schedule v5.MD - AgriID; ADR-0002).",
        "pii_note": "handles auth and holds the most PII in the system",
        "extra_never": "- Never store plaintext credentials or tokens; never weaken\n"
        "  require_auth outside specs D08-09.",
    },
    "coins": {
        "purpose": "AgriCoins ledger: balances, rewards, redemptions.",
        "spec": "Phase 1 plan - AgriCoins (docs/Execution schedule v5.MD).",
        "pii_note": "handles balance data tied to identities",
        "extra_never": "- Never mutate balances outside an append-only ledger entry;\n"
        "  the `billing_enabled` flag gates real-money interplay.",
    },
    "directory": {
        "purpose": "Directory Engine E1: org/place profiles, branches, categories,\n"
        "verification, claims - the workhorse engine. Also hosts the catalog\n"
        "surface (D17, engine E2 in basic form) under /catalog/*: vertical\n"
        "registry, append-only spec-schema versions, schema-validated products.\n"
        "Product specs validate against the PINNED schema version on write,\n"
        "never on read; product images go through shared.media.reencode_image\n"
        "only (lint-gated) and serve from the media domain. Also hosts D18's\n"
        "reviews engine under /reviews + /admin/reviews: UGC pending-default\n"
        "moderation with cached rating aggregates, and a leads engine under\n"
        "/leads: guest submission (optional_auth), coverage(pincode) x\n"
        "category routing, owner inbox/responses/stats. Contact reveal\n"
        "(/directory/branches/{id}/reveal) is daily-capped, fail-closed, and\n"
        "appends to an append-only leads.contact_reveals DPDP log. Emits\n"
        "review.approved, lead.created, lead.responded on the directory\n"
        "event stream. D26 adds owner tier-selection (intent only;\n"
        "subscription_tier is admin-set via /admin/directory .../tier, audited),\n"
        "premium-first covers() ordering, a public profile-view beacon\n"
        "(/directory/businesses/{slug}/view, daily-rotating pseudonym,\n"
        "append-only), and owner analytics (/directory/businesses/{id}/analytics).",
        "spec": "docs/Execution schedule v5.MD SS E1 (~60% of verticals build on it).",
        "pii_note": "holds business contact data (phones, emails)",
        "extra_never": "- Never render contact details without the lead/verification\n"
        "  gate the vertical registry specifies.",
    },
    "leads": {
        "purpose": "Leads/intent matchmaking E4: buy/sell intents matched on\n"
        "category x geo x attributes.",
        "spec": "docs/Execution schedule v5.MD SS E4.",
        "pii_note": "carries buyer/seller contact intents (PII-dense)",
        "extra_never": "- Never reveal counterparty contacts before the verification\n"
        "  gate; import/export leads are business-verified only.",
    },
    "content": {
        "purpose": "Content Engine E6: articles, news, guides, events - i18n'd and\n"
        "taggable by vertical + geo.",
        "spec": "docs/Execution schedule v5.MD SS E6.",
        "pii_note": "is mostly public content but comments/authorship attach to users",
        "extra_never": "- Never publish without the pending-by-default moderation\n"
        "  flow; slugs are immutable (ADR-0006).",
    },
    "market_data": {
        "purpose": "Data/Info Engine E5: admin-managed structured datasets (mandi,\n"
        "schemes, helplines) rendered as browsable reference sections.",
        "spec": "docs/Execution schedule v5.MD SS E5.",
        "pii_note": "should hold no personal data - datasets are public records",
        "extra_never": "- Never serve a dataset without source + as-of date metadata\n"
        "  (data.gov.in sourcing traps: 10-row cap, case-sensitive filters).",
    },
    "ads": {
        "purpose": "Ads: flat-rate slot inventory targeted by vertical x geo x role\n"
        "x language, with admin approval.",
        "spec": "docs/Execution schedule v5.MD SS5 (Ads v2 at D85).",
        "pii_note": "handles advertiser billing contacts",
        "extra_never": "- Never serve an unlabeled ad ('Sponsored' always); the\n"
        "  `ads_enabled` flag gates the whole module.",
    },
    "notify": {
        "purpose": "Notifications fan-out: in-app now; email, SMS/WhatsApp later.",
        "spec": "docs/Execution schedule v5.MD - cross-cutting services.",
        "pii_note": "addresses messages to phones/emails by definition",
        "extra_never": "- Never log message bodies or destination addresses; log\n"
        "  message ids and template ids only.",
    },
    "search": {
        "purpose": "Meilisearch indexing + query facade for all modules.",
        "spec": "docs/Execution schedule v5.MD - cross-cutting; ADR-0007.",
        "pii_note": "must not index private fields into public documents",
        "extra_never": "- Never index a field the owning module marks private;\n"
        "  Postgres is the source of truth - indexes are rebuildable.",
    },
    "billing": {
        "purpose": "Razorpay payments: subscriptions, slot purchases, invoices.",
        "spec": "docs/Execution schedule v5.MD - monetisation stages.",
        "pii_note": "touches payment metadata (never store card/bank data)",
        "extra_never": "- Never handle raw card data (Razorpay hosted flows only);\n"
        "  the `billing_enabled` flag is the master kill switch.",
    },
    "ops": {
        "purpose": "Ops Console backend: unified moderation queue fan-in\n"
        "(shared/moderation registry) + feature-flag switches.",
        "spec": "Sprint2 spec pack D21.",
        "pii_note": "fans other modules' pending items into one queue",
        "extra_never": "- Never decide or commit on a source's behalf - the\n"
        "  registered ModerationSource owns its FOR UPDATE service and audit()\n"
        "  call; this module only sequences commit -> best-effort publish.\n"
        "- Never flip a flag outside the super_admin gate; a flag flip is a\n"
        "  business-level act.",
    },
    "ai": {
        "purpose": "AI features: content generation at scale, assistants.",
        "spec": "docs/Execution schedule v5.MD SS4.3 (SEO page factory copy).",
        "pii_note": "must never send user PII to external model APIs",
        "extra_never": "- Never auto-publish generated copy without the\n"
        "  human-spot-check flow; label AI-generated content as such.",
    },
}


def main() -> None:
    root = Path(__file__).resolve().parent.parent / "modules"
    for name, cfg in MODULES.items():
        target = root / name / "CLAUDE.md"
        target.write_text(TEMPLATE.format(name=name, **cfg), encoding="utf-8", newline="\n")
        print(f"wrote {target}")  # noqa: T201 - CLI output


if __name__ == "__main__":
    main()
